spring.application.name=mascotas

spring.datasource.url=jdbc:mysql://mysql-e766c8a-lr616944-b2a4.j.aivencloud.com:13824/mascotas?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_0tfBFB_ZUKcXx7csZzn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
